import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import test from "node:test";

const execFileAsync = promisify(execFile);
const repositoryRoot = new URL("../", import.meta.url);
const runtimeConsumers = [
  "app/guide/page.js",
  "app/guide/[segment]/page.js",
  "app/guide/[segment]/[slug]/page.js",
  "app/en/guide/page.js",
  "app/en/guide/[segment]/page.js",
  "app/en/guide/[segment]/[slug]/page.js",
  "components/pages/guide-route.js",
  "lib/public-route-inventory.mjs"
];

test("Guide runtime consumers use a filesystem-free validated inventory", async () => {
  const [runtimeSource, generatedSource, sitemapSource, consumerSources] = await Promise.all([
    readFile(new URL("../lib/guides/guide-runtime.mjs", import.meta.url), "utf8"),
    readFile(new URL("../lib/guides/guide-runtime-inventory.generated.mjs", import.meta.url), "utf8"),
    readFile(new URL("../app/sitemap.js", import.meta.url), "utf8"),
    Promise.all(runtimeConsumers.map(async (pathname) => ({
      pathname,
      source: await readFile(new URL(`../${pathname}`, import.meta.url), "utf8")
    })))
  ]);

  for (const { pathname, source } of consumerSources) {
    assert.doesNotMatch(source, /guide-loader\.mjs/, `${pathname} must not import the filesystem loader`);
    assert.match(source, /guide-runtime\.mjs/, `${pathname} must import the runtime facade`);
  }
  assert.doesNotMatch(sitemapSource, /guide-loader\.mjs/);
  assert.match(sitemapSource, /public-route-inventory\.mjs/);
  assert.doesNotMatch(runtimeSource, /node:(?:fs|path)|content\/guides|import\.meta\.url/);
  assert.doesNotMatch(generatedSource, /node:(?:fs|path)|content\/guides|import\.meta\.url/);
});

test("tracked Guide runtime inventory matches the fully validated source", async () => {
  const [{ loadGuideInventory }, { guideRuntimeInventory }] = await Promise.all([
    import(new URL("../lib/guides/guide-loader.mjs", import.meta.url)),
    import(new URL("../lib/guides/guide-runtime-inventory.generated.mjs", import.meta.url))
  ]);

  assert.deepEqual(guideRuntimeInventory, await loadGuideInventory());
});

test("Guide runtime inventory check accepts current generated bytes", async () => {
  const { stdout, stderr } = await execFileAsync(
    process.execPath,
    ["scripts/generate-guide-runtime-inventory.mjs", "--check"],
    { cwd: repositoryRoot }
  );

  assert.equal(stderr, "");
  assert.match(stdout, /Guide runtime inventory is current/);
});

test("Guide runtime inventory check accepts canonical bytes after a CRLF checkout", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "kurodev-guide-runtime-crlf-"));
  const crlfArtifact = join(temporaryDirectory, "guide-runtime-inventory.generated.mjs");
  const generatedSource = await readFile(
    new URL("../lib/guides/guide-runtime-inventory.generated.mjs", import.meta.url),
    "utf8"
  );
  await writeFile(crlfArtifact, generatedSource.replace(/\r?\n/g, "\r\n"), "utf8");

  try {
    const { stdout, stderr } = await execFileAsync(
      process.execPath,
      ["scripts/generate-guide-runtime-inventory.mjs", "--check", "--output", pathToFileURL(crlfArtifact).href],
      { cwd: repositoryRoot }
    );

    assert.equal(stderr, "");
    assert.match(stdout, /Guide runtime inventory is current/);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});

test("Guide runtime inventory check rejects stale generated bytes", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "kurodev-guide-runtime-"));
  const staleArtifact = join(temporaryDirectory, "guide-runtime-inventory.generated.mjs");
  await writeFile(staleArtifact, "export const guideRuntimeInventory = [];\n", "utf8");

  try {
    await assert.rejects(
      execFileAsync(
        process.execPath,
        ["scripts/generate-guide-runtime-inventory.mjs", "--check", "--output", pathToFileURL(staleArtifact).href],
        { cwd: repositoryRoot }
      ),
      (error) => error.code === 1 && /Guide runtime inventory is stale/.test(error.stderr)
    );
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});
